#!/usr/bin/env bash
set -euo pipefail

# Install the bridge environment and marketplace-backed GPT Relay plugin for
# every Codex CLI session launched by this user.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="${HOME}/.config/gpt-relay"
ENV_FILE="${CONFIG_DIR}/env.sh"
MARKETPLACE_NAME="gpt-relay-host-bridge"
MARKETPLACE_SOURCE="ChingFuHan/My_relay_test"
BRIDGE_URL="${GPT_RELAY_HOST_BRIDGE_URL:-}"
BRIDGE_TOKEN="${GPT_RELAY_HOST_BRIDGE_TOKEN:-}"
SKIP_PLUGIN=false

usage() {
  cat <<'EOF'
Usage:
  bash scripts/install-global-codex-relay.sh \
    --bridge-url http://HOST:8765 \
    --bridge-token YOUR_TOKEN

Options:
  --bridge-url URL          GPT Relay host-bridge URL.
  --bridge-token TOKEN      Host-bridge bearer token.
  --marketplace-source SRC  GitHub owner/repo, Git URL, or local repo path.
  --skip-plugin             Do not add/install the Codex plugin.
  --help                    Show this help.

Without --bridge-url/--bridge-token, existing GPT_RELAY_* environment values
are used. If neither exists, an editable env.sh template is created.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --bridge-url)
      BRIDGE_URL="${2:?Missing value for --bridge-url}"
      shift 2
      ;;
    --bridge-token)
      BRIDGE_TOKEN="${2:?Missing value for --bridge-token}"
      shift 2
      ;;
    --marketplace-source)
      MARKETPLACE_SOURCE="${2:?Missing value for --marketplace-source}"
      shift 2
      ;;
    --skip-plugin)
      SKIP_PLUGIN=true
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if { [ -n "${BRIDGE_URL}" ] && [ -z "${BRIDGE_TOKEN}" ]; } || \
   { [ -z "${BRIDGE_URL}" ] && [ -n "${BRIDGE_TOKEN}" ]; }; then
  printf '%s\n' '--bridge-url and --bridge-token must be supplied together.' >&2
  exit 2
fi

install -d -m 700 "${CONFIG_DIR}"

if [ -n "${BRIDGE_URL}" ]; then
  umask 077
  {
    printf '%s\n' '# Generated by install-global-codex-relay.sh'
    printf 'export GPT_RELAY_BROWSER_PROVIDER=%q\n' 'host-bridge'
    printf 'export GPT_RELAY_HOST_BRIDGE_URL=%q\n' "${BRIDGE_URL}"
    printf 'export GPT_RELAY_HOST_BRIDGE_TOKEN=%q\n' "${BRIDGE_TOKEN}"
  } > "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
  printf 'Configured %s\n' "${ENV_FILE}"
elif [ ! -f "${ENV_FILE}" ]; then
  install -m 600 "${SCRIPT_DIR}/gpt-relay-env.example.sh" "${ENV_FILE}"
  printf 'Created editable bridge config: %s\n' "${ENV_FILE}"
else
  printf 'Kept existing bridge config: %s\n' "${ENV_FILE}"
fi

SHELL_NAME="$(basename "${SHELL:-bash}")"
case "${SHELL_NAME}" in
  zsh) RC_FILE="${HOME}/.zshrc" ;;
  *) RC_FILE="${HOME}/.bashrc" ;;
esac
SOURCE_LINE='[ -f "$HOME/.config/gpt-relay/env.sh" ] && . "$HOME/.config/gpt-relay/env.sh"'
touch "${RC_FILE}"
if ! grep -Fqx "${SOURCE_LINE}" "${RC_FILE}"; then
  printf '\n%s\n' "${SOURCE_LINE}" >> "${RC_FILE}"
  printf 'Added GPT Relay environment loading to %s\n' "${RC_FILE}"
else
  printf 'Kept GPT Relay environment loading in %s\n' "${RC_FILE}"
fi

if [ "${SKIP_PLUGIN}" = false ]; then
  command -v codex >/dev/null || {
    printf '%s\n' 'codex was not found in PATH; bridge environment was configured but plugin installation was skipped.' >&2
    exit 1
  }

  if ! codex plugin marketplace list | grep -Fq "Marketplace \`${MARKETPLACE_NAME}\`"; then
    if [ -d "${MARKETPLACE_SOURCE}" ]; then
      codex plugin marketplace add "${MARKETPLACE_SOURCE}"
    else
      codex plugin marketplace add "${MARKETPLACE_SOURCE}" --ref main
    fi
  else
    codex plugin marketplace upgrade "${MARKETPLACE_NAME}"
  fi
  codex plugin add "gpt-relay@${MARKETPLACE_NAME}"
fi

cat <<EOF

Global setup complete.

Open a new shell (or run: . "${RC_FILE}"), then start Codex in any directory.
In the Codex composer, type @, select GPT Relay, and enter the task for ChatGPT.
The plugin MCP relay reads ${ENV_FILE} itself, including when Codex was not started from this shell.

The bridge must still be running and ChatGPT must remain logged in on its Chrome profile.
EOF
