#!/usr/bin/env bash
set -euo pipefail

# Install the pieces that must live outside a repository: environment defaults,
# native Codex prompt commands, and the marketplace-backed GPT Relay plugin.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_DIR="${HOME}/.config/gpt-relay"
ENV_FILE="${CONFIG_DIR}/env.sh"
PROMPT_DIR="${HOME}/.codex/prompts"
MARKETPLACE_NAME="gpt-relay-host-bridge"
MARKETPLACE_SOURCE="ChingFuHan/My_relay_test"
BRIDGE_URL="${GPT_RELAY_HOST_BRIDGE_URL:-}"
BRIDGE_TOKEN="${GPT_RELAY_HOST_BRIDGE_TOKEN:-}"
FORCE_PROMPTS=false
SKIP_PLUGIN=false

usage() {
  cat <<'EOF'
Usage:
  bash scripts/install-global-codex-relay.sh \
    --bridge-url http://HOST:8765 \
    --bridge-token YOUR_TOKEN

Options:
  --bridge-url URL          GPT Relay host-bridge URL.
  --bridge-token TOKEN      Host-bridge bearer token.
  --marketplace-source SRC  GitHub owner/repo, Git URL, or local repo path.
  --force-prompts           Replace existing ~/.codex/prompts GPT Relay files.
  --skip-plugin             Do not add/install the Codex plugin.
  --help                    Show this help.

Without --bridge-url/--bridge-token, existing GPT_RELAY_* environment values
are used. If neither exists, an editable env.sh template is created.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --bridge-url)
      BRIDGE_URL="${2:?Missing value for --bridge-url}"
      shift 2
      ;;
    --bridge-token)
      BRIDGE_TOKEN="${2:?Missing value for --bridge-token}"
      shift 2
      ;;
    --marketplace-source)
      MARKETPLACE_SOURCE="${2:?Missing value for --marketplace-source}"
      shift 2
      ;;
    --force-prompts)
      FORCE_PROMPTS=true
      shift
      ;;
    --skip-plugin)
      SKIP_PLUGIN=true
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if { [ -n "${BRIDGE_URL}" ] && [ -z "${BRIDGE_TOKEN}" ]; } || \
   { [ -z "${BRIDGE_URL}" ] && [ -n "${BRIDGE_TOKEN}" ]; }; then
  printf '%s\n' '--bridge-url and --bridge-token must be supplied together.' >&2
  exit 2
fi

install -d -m 700 "${CONFIG_DIR}" "${PROMPT_DIR}"

if [ -n "${BRIDGE_URL}" ]; then
  umask 077
  {
    printf '%s\n' '# Generated by install-global-codex-relay.sh'
    printf 'export GPT_RELAY_BROWSER_PROVIDER=%q\n' 'host-bridge'
    printf 'export GPT_RELAY_HOST_BRIDGE_URL=%q\n' "${BRIDGE_URL}"
    printf 'export GPT_RELAY_HOST_BRIDGE_TOKEN=%q\n' "${BRIDGE_TOKEN}"
  } > "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
  printf 'Configured %s\n' "${ENV_FILE}"
elif [ ! -f "${ENV_FILE}" ]; then
  install -m 600 "${SCRIPT_DIR}/gpt-relay-env.example.sh" "${ENV_FILE}"
  printf 'Created editable bridge config: %s\n' "${ENV_FILE}"
else
  printf 'Kept existing bridge config: %s\n' "${ENV_FILE}"
fi

SHELL_NAME="$(basename "${SHELL:-bash}")"
case "${SHELL_NAME}" in
  zsh) RC_FILE="${HOME}/.zshrc" ;;
  *) RC_FILE="${HOME}/.bashrc" ;;
esac
SOURCE_LINE='[ -f "$HOME/.config/gpt-relay/env.sh" ] && . "$HOME/.config/gpt-relay/env.sh"'
touch "${RC_FILE}"
if ! grep -Fqx "${SOURCE_LINE}" "${RC_FILE}"; then
  printf '\n%s\n' "${SOURCE_LINE}" >> "${RC_FILE}"
  printf 'Added GPT Relay environment loading to %s\n' "${RC_FILE}"
else
  printf 'Kept GPT Relay environment loading in %s\n' "${RC_FILE}"
fi

for template in "${REPO_ROOT}"/templates/codex-prompts/*.md; do
  target="${PROMPT_DIR}/$(basename "${template}")"
  if [ -e "${target}" ] && [ "${FORCE_PROMPTS}" != true ]; then
    printf 'Kept existing prompt: %s\n' "${target}"
  else
    install -m 600 "${template}" "${target}"
    printf 'Installed prompt: %s\n' "${target}"
  fi
done

if [ "${SKIP_PLUGIN}" = false ]; then
  command -v codex >/dev/null || {
    printf '%s\n' 'codex was not found in PATH; prompt files were installed but the plugin was skipped.' >&2
    exit 1
  }

  if ! codex plugin marketplace list | grep -Fq "Marketplace \`${MARKETPLACE_NAME}\`"; then
    if [ -d "${MARKETPLACE_SOURCE}" ]; then
      codex plugin marketplace add "${MARKETPLACE_SOURCE}"
    else
      codex plugin marketplace add "${MARKETPLACE_SOURCE}" --ref main
    fi
  else
    codex plugin marketplace upgrade "${MARKETPLACE_NAME}"
  fi
  codex plugin add "gpt-relay@${MARKETPLACE_NAME}"
fi

cat <<EOF

Global setup complete.

Exit every already-running Codex CLI process first. Then open a new shell (or run: . "${RC_FILE}")
and start a new Codex process in any directory. `/new` and switching to Plan mode do not reload
custom prompts.
Use these native Codex commands:
  /prompts:chatgpt <task>
  /prompts:gpt <task>
  /prompts:chatgpt-continue query=<topic> :: <next instruction>
  /prompts:chatgpt-poll query=<topic>

The bridge must still be running and ChatGPT must remain logged in on its Chrome profile.
EOF
